export const upgrades = [
            {   
            id: 'programmerSocks',
            name:'Programmer Socks',
            imgSrc:'./images/programmersocks.jpeg',
            imgAlt:'Programmer socks',
            price: 100,
            monstersLeftToBuy: 999,
            multiplier: 0.5,
            description:'Sokker som gir deg en buff på programmering. Debuff på straightness. Følger med vscode themes!',
            amount:0,
            },
            {
            id: 'miku',
            name:'Miku',
            imgSrc:'./images/miku.jpeg',
            imgAlt:'Miku',
            price: 500,
            monstersLeftToBuy: 999,
            multiplier: 10,
            description:'Beste vocaloid artisten. En kjærlig og fantastisk vocaloid som eier hele verden og skaper glede.',
            amount:0,
            },
            {
            id: 'neeko',
            name:'Neeko',
            imgSrc:'./images/neeko.png',
            imgAlt:'Neeko',
            price: 1000,
            monstersLeftToBuy: 999,
            multiplier: 100,        
            description:'En vill og quirky kvinne med lesbiske tendenser. Shuma sniffer og hella cute. Bird fetishiser.',
            amount:0,
            },
];
